import contracts from './contracts.mjs'

export const QuoteToken = {
    'BNB': 'BNB',
    'RUNE': 'RUNE',
    'EL': 'EL',
    'ELD': 'ELD',
    'TIR': 'TIR',
    'NEF': 'NEF',
    'ITH': 'ITH',
    'TAL': 'TAL',
    'RAL': 'RAL',
    'AMN': 'AMN',
    'BUSD': 'BUSD',
    'USDC': 'USDC',
    'BTCB': 'BTCB',
    'SLME': 'SLME',
    'ETH': 'ETH',
}

export const MAINNET = 56
export const TESTNET = 97

export const CURRENT_FARM_SYMBOL = ''

const farms = [
  {
    fid: 0,
    pid: 0,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '96X',
    poolWeight: 9600,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'RUNE-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xf9444c39bbdcc3673033609204f8da00d1ae3f52',
      [TESTNET]: '',
    },
    tokenSymbol: 'RUNE',
    tokenAddresses: contracts.rune,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 1,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '96X',
    poolWeight: 9600,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'RUNE-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0x68513e24495b9d1d1fedee0906872a96858e8ad2',
      [TESTNET]: '',
    },
    tokenSymbol: 'RUNE',
    tokenAddresses: contracts.rune,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 2,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '4X',
    poolWeight: 400, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'RAL',
    lpAddresses: contracts.ral,
    tokenLpAddresses: {
      [MAINNET]: '0xc502b2595f76dd39f41a1ff640a7e439c27da95f',
      [TESTNET]: '',
    },
    tokenSymbol: 'RAL',
    tokenAddresses: contracts.ral,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 3,
    risk: 1,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100,
    depositFeeBP: 40,
    inactive: false,
    lpSymbol: 'BUSD-BNB LP',
    lpAddresses: {
      [MAINNET]: '0x1b96b92314c44b159149f7e0303511fb2fc4774f',
      [TESTNET]: '',
    },
    tokenSymbol: 'BUSD',
    tokenAddresses: contracts.busd,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 4,
    risk: 1,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100,
    depositFeeBP: 40,
    inactive: false,
    lpSymbol: 'BTCB-BNB LP',
    lpAddresses: {
      [MAINNET]: '0x7561EEe90e24F3b348E1087A005F78B4c8453524',
      [TESTNET]: '',
    },
    tokenSymbol: 'BTCB',
    tokenAddresses: contracts.btcb,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 5,
    risk: 1,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100,
    depositFeeBP: 40,
    inactive: false,
    lpSymbol: 'USDT-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xc15fa3e22c912a276550f3e5fe3b0deb87b55acd',
      [TESTNET]: '',
    },
    tokenSymbol: 'USDT',
    tokenAddresses: contracts.usdt,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 6,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '12X',
    poolWeight: 1200,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'EL-RUNE LP',
    lpAddresses: {
      [MAINNET]: '0xba35b17bd3e993812b0455dfc4d0eafa41ade9cb',
      [TESTNET]: '',
    },
    tokenSymbol: 'EL',
    tokenAddresses: contracts.el,
    quoteTokenSymbol: QuoteToken.RUNE,
    quoteTokenAdresses: contracts.rune,
  },
  {
    fid: 0,
    pid: 7,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'EL-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xa7687d322cb9c3cf98679d164b7e45f8ede837bc',
      [TESTNET]: '',
    },
    tokenSymbol: 'EL',
    tokenAddresses: contracts.el,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 8,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'EL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xdd428edb5176908ecf740dfa8a57efbc36b5d5eb',
      [TESTNET]: '',
    },
    tokenSymbol: 'EL',
    tokenAddresses: contracts.el,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 9,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '96X',
    poolWeight: 9600,
    isTokenOnly: true,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'RUNE',
    lpAddresses: contracts.rune,
    tokenLpAddresses: {
      [MAINNET]: '0x68513e24495b9d1d1fedee0906872a96858e8ad2',
      [TESTNET]: '',
    },
    tokenSymbol: 'RUNE',
    tokenAddresses: contracts.rune,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 10,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'EL',
    lpAddresses: contracts.el,
    tokenLpAddresses: {
      [MAINNET]: '0xdd428edb5176908ecf740dfa8a57efbc36b5d5eb',
      [TESTNET]: '',
    },
    tokenSymbol: 'EL',
    tokenAddresses: contracts.el,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 11,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'TIR',
    lpAddresses: contracts.tir,
    tokenLpAddresses: {
      [MAINNET]: '0x1d779adbdc65bf45a6d15c625daac98f1ef3c150',
      [TESTNET]: '',
    },
    tokenSymbol: 'TIR',
    tokenAddresses: contracts.tir,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 12,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '12X',
    poolWeight: 1200,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'TIR-RUNE LP',
    lpAddresses: {
      [MAINNET]: '0xb6443654db94dbe382782fcd7b0deb28449ee0f1',
      [TESTNET]: '',
    },
    tokenSymbol: 'TIR',
    tokenAddresses: contracts.tir,
    quoteTokenSymbol: QuoteToken.RUNE,
    quoteTokenAdresses: contracts.rune,
  },
  {
    fid: 0,
    pid: 13,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'TIR-BNB LP',
    lpAddresses: {
      [MAINNET]: '0x59dc0d5b2c993d4e448c0c886f0a6badb203d26b',
      [TESTNET]: '',
    },
    tokenSymbol: 'TIR',
    tokenAddresses: contracts.tir,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 14,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'TIR-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0x1d779adbdc65bf45a6d15c625daac98f1ef3c150',
      [TESTNET]: '',
    },
    tokenSymbol: 'TIR',
    tokenAddresses: contracts.tir,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 15,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '24X',
    poolWeight: 2400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'TIR-EL LP',
    lpAddresses: {
      [MAINNET]: '0x942f0167258dccfca16d4e2f27a1630cf5679941',
      [TESTNET]: '',
    },
    tokenSymbol: 'TIR',
    tokenAddresses: contracts.tir,
    quoteTokenSymbol: QuoteToken.EL,
    quoteTokenAdresses: contracts.el,
  },
  {
    fid: 0,
    pid: 16,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'ELD',
    lpAddresses: contracts.eld,
    tokenLpAddresses: {
      [MAINNET]: '0x3ee04fd83329f165012919102070e6fdc37181c2',
      [TESTNET]: '',
    },
    tokenSymbol: 'ELD',
    tokenAddresses: contracts.eld,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 17,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'ELD-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0x3ee04fd83329f165012919102070e6fdc37181c2',
      [TESTNET]: '',
    },
    tokenSymbol: 'ELD',
    tokenAddresses: contracts.eld,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 18,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'NEF',
    lpAddresses: contracts.nef,
    tokenLpAddresses: {
      [MAINNET]: '0xa919b33bfec9fff5577f03857e48f8251f219966',
      [TESTNET]: '',
    },
    tokenSymbol: 'NEF',
    tokenAddresses: contracts.nef,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 19,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '24X',
    poolWeight: 2400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'NEF-RUNE LP',
    lpAddresses: {
      [MAINNET]: '0xfd0cca3974c525477a36aba59ae1d63bf6084aa3',
      [TESTNET]: '',
    },
    tokenSymbol: 'NEF',
    tokenAddresses: contracts.nef,
    quoteTokenSymbol: QuoteToken.RUNE,
    quoteTokenAdresses: contracts.rune,
  },
  {
    fid: 0,
    pid: 20,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'NEF-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xdf3ec0f20fd61491c54a3528554ba125e56d9894',
      [TESTNET]: '',
    },
    tokenSymbol: 'NEF',
    tokenAddresses: contracts.nef,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 21,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'NEF-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xa919b33bfec9fff5577f03857e48f8251f219966',
      [TESTNET]: '',
    },
    tokenSymbol: 'NEF',
    tokenAddresses: contracts.nef,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 22,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '24X',
    poolWeight: 2400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'NEF-EL LP',
    lpAddresses: {
      [MAINNET]: '0x4c0bce2bf4390db5be0b749d5a27aec4b892dae0',
      [TESTNET]: '',
    },
    tokenSymbol: 'NEF',
    tokenAddresses: contracts.nef,
    quoteTokenSymbol: QuoteToken.EL,
    quoteTokenAdresses: contracts.el,
  },
  {
    fid: 0,
    pid: 23,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '24X',
    poolWeight: 2400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'NEF-TIR LP',
    lpAddresses: {
      [MAINNET]: '0x0c54ab9bed8765958a9b3ac7fd64a264c94f6585',
      [TESTNET]: '',
    },
    tokenSymbol: 'NEF',
    tokenAddresses: contracts.nef,
    quoteTokenSymbol: QuoteToken.TIR,
    quoteTokenAdresses: contracts.tir,
  },
  {
    fid: 0,
    pid: 24,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'ITH-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xd2d495b17ca6433d224146fdd99319a812695ccc',
      [TESTNET]: '',
    },
    tokenSymbol: 'ITH',
    tokenAddresses: contracts.ith,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 25,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'ITH-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xb9c25e0ae0b604b7454d6bc884b030c82e29e2f2',
      [TESTNET]: '',
    },
    tokenSymbol: 'ITH',
    tokenAddresses: contracts.ith,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 26,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '24X',
    poolWeight: 2400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'ITH-NEF LP',
    lpAddresses: {
      [MAINNET]: '0x596d992d53dfcef2aa2651fbba292438d56138fb',
      [TESTNET]: '',
    },
    tokenSymbol: 'ITH',
    tokenAddresses: contracts.ith,
    quoteTokenSymbol: QuoteToken.NEF,
    quoteTokenAdresses: contracts.nef,
  },
  {
    fid: 0,
    pid: 27,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '24X',
    poolWeight: 2400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'ITH-ELD LP',
    lpAddresses: {
      [MAINNET]: '0x3f1c0825f8ec6df33a1830ea97616371d508f84b',
      [TESTNET]: '',
    },
    tokenSymbol: 'ITH',
    tokenAddresses: contracts.ith,
    quoteTokenSymbol: QuoteToken.ELD,
    quoteTokenAdresses: contracts.eld,
  },
  {
    fid: 0,
    pid: 28,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'ITH',
    lpAddresses: contracts.ith,
    tokenLpAddresses: {
      [MAINNET]: '0xb9c25e0ae0b604b7454d6bc884b030c82e29e2f2',
      [TESTNET]: '',
    },
    tokenSymbol: 'ITH',
    tokenAddresses: contracts.ith,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 29,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'TAL-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xdbf6a6da052ccb1a29a1d86de5fd51acdab5b055',
      [TESTNET]: '',
    },
    tokenSymbol: 'TAL',
    tokenAddresses: contracts.tal,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 30,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'TAL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xc434b517288086043cb3f0a7c2f0eb4c37046206',
      [TESTNET]: '',
    },
    tokenSymbol: 'TAL',
    tokenAddresses: contracts.tal,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 31,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'TAL',
    lpAddresses: contracts.tal,
    tokenLpAddresses: {
      [MAINNET]: '0xc434b517288086043cb3f0a7c2f0eb4c37046206',
      [TESTNET]: '',
    },
    tokenSymbol: 'TAL',
    tokenAddresses: contracts.tal,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 32,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'RAL-BNB LP',
    lpAddresses: {
      [MAINNET]: '0x15e83deb7097366c44ae19bcea106a5041bf88ed',
      [TESTNET]: '',
    },
    tokenSymbol: 'RAL',
    tokenAddresses: contracts.ral,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 33,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'RAL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xc502b2595f76dd39f41a1ff640a7e439c27da95f',
      [TESTNET]: '',
    },
    tokenSymbol: 'RAL',
    tokenAddresses: contracts.ral,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 34,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'ORT-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xcd433d8befea6364b50fc8ccc8a2f78a8d687a73',
      [TESTNET]: '',
    },
    tokenSymbol: 'ORT',
    tokenAddresses: contracts.ort,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 35,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'ORT-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0x8B57F9CB80e4984Df95f80342ed65d8ec0640328',
      [TESTNET]: '',
    },
    tokenSymbol: 'ORT',
    tokenAddresses: contracts.ort,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 36,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'ORT',
    lpAddresses: contracts.ort,
    tokenLpAddresses: {
      [MAINNET]: '0x8B57F9CB80e4984Df95f80342ed65d8ec0640328',
      [TESTNET]: '',
    },
    tokenSymbol: 'ORT',
    tokenAddresses: contracts.ort,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 37,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'THUL-BNB LP',
    lpAddresses: {
      [MAINNET]: '0x357264c2c01b854e6361869d18293fc1445b9759',
      [TESTNET]: '',
    },
    tokenSymbol: 'THUL',
    tokenAddresses: contracts.thul,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 38,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'THUL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0x159c3a50515207a2344b1fb1f831921d452abfa1',
      [TESTNET]: '',
    },
    tokenSymbol: 'THUL',
    tokenAddresses: contracts.thul,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 39,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'THUL',
    lpAddresses: contracts.thul,
    tokenLpAddresses: {
      [MAINNET]: '0x159c3a50515207a2344b1fb1f831921d452abfa1',
      [TESTNET]: '',
    },
    tokenSymbol: 'THUL',
    tokenAddresses: contracts.thul,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 40,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'AMN-BNB LP',
    lpAddresses: {
      [MAINNET]: '0x894d67f2800fc204c9b66953f7175f218419a30c',
      [TESTNET]: '',
    },
    tokenSymbol: 'AMN',
    tokenAddresses: contracts.amn,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 41,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'AMN-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xa63402f5ca52d5e7c3441e41a41ba3445429bb4f',
      [TESTNET]: '',
    },
    tokenSymbol: 'AMN',
    tokenAddresses: contracts.amn,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 42,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'AMN',
    lpAddresses: contracts.amn,
    tokenLpAddresses: {
      [MAINNET]: '0xa63402f5ca52d5e7c3441e41a41ba3445429bb4f',
      [TESTNET]: '',
    },
    tokenSymbol: 'AMN',
    tokenAddresses: contracts.amn,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 43,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'SOL-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xd11327fbb5cd97e9412f8e430b479d092f4a9c70',
      [TESTNET]: '',
    },
    tokenSymbol: 'SOL',
    tokenAddresses: contracts.sol,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 44,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'SOL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xb95a11a4aff2a671e0b4dc0c3e4981371a4bdd33',
      [TESTNET]: '',
    },
    tokenSymbol: 'SOL',
    tokenAddresses: contracts.sol,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 45,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'SOL',
    lpAddresses: contracts.sol,
    tokenLpAddresses: {
      [MAINNET]: '0xb95a11a4aff2a671e0b4dc0c3e4981371a4bdd33',
      [TESTNET]: '',
    },
    tokenSymbol: 'SOL',
    tokenAddresses: contracts.sol,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 46,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'SHAEL-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xe499d2144a8cf9dc85f92629afc431334a088b1b',
      [TESTNET]: '',
    },
    tokenSymbol: 'SHAEL',
    tokenAddresses: contracts.shael,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 47,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'SHAEL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0x22ac4bf4a66631f45f23d325a227e3b9fb647a4e',
      [TESTNET]: '',
    },
    tokenSymbol: 'SHAEL',
    tokenAddresses: contracts.shael,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 48,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'SHAEL',
    lpAddresses: contracts.shael,
    tokenLpAddresses: {
      [MAINNET]: '0x22ac4bf4a66631f45f23d325a227e3b9fb647a4e',
      [TESTNET]: '',
    },
    tokenSymbol: 'SHAEL',
    tokenAddresses: contracts.shael,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 49,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'DOL-BNB LP',
    lpAddresses: {
      [MAINNET]: '0x4dcddaa11e2bd78951b7811eeb3fdac941f23ea3',
      [TESTNET]: '',
    },
    tokenSymbol: 'DOL',
    tokenAddresses: contracts.dol,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 50,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'DOL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xb78e0c6abe96a4cdf584d63bed3c4a4ed3d409f3',
      [TESTNET]: '',
    },
    tokenSymbol: 'DOL',
    tokenAddresses: contracts.dol,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 51,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'DOL',
    lpAddresses: contracts.dol,
    tokenLpAddresses: {
      [MAINNET]: '0xb78e0c6abe96a4cdf584d63bed3c4a4ed3d409f3',
      [TESTNET]: '',
    },
    tokenSymbol: 'DOL',
    tokenAddresses: contracts.dol,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 52,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'HEL-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xc2ac7b7e0c0968d531b95a7dad1edff7cf8586cc',
      [TESTNET]: '',
    },
    tokenSymbol: 'HEL',
    tokenAddresses: contracts.hel,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 53,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'HEL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0x8de5b59c7a1a1e19c6bed13546e5d093762ab7cf',
      [TESTNET]: '',
    },
    tokenSymbol: 'HEL',
    tokenAddresses: contracts.hel,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 54,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'HEL',
    lpAddresses: contracts.hel,
    tokenLpAddresses: {
      [MAINNET]: '0x8de5b59c7a1a1e19c6bed13546e5d093762ab7cf',
      [TESTNET]: '',
    },
    tokenSymbol: 'HEL',
    tokenAddresses: contracts.hel,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 55,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    isRetired: true,
    inactive: false,
    lpSymbol: 'IO-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xc1c951802767b6ae45918ad3acda6a4937b8fb36',
      [TESTNET]: '',
    },
    tokenSymbol: 'IO',
    tokenAddresses: contracts.io,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 56,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'IO-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xa6fc895186914b5621776ea8dcd5ccdd1f0035d1',
      [TESTNET]: '',
    },
    tokenSymbol: 'IO',
    tokenAddresses: contracts.io,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 57,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'IO',
    lpAddresses: contracts.io,
    tokenLpAddresses: {
      [MAINNET]: '0xa6fc895186914b5621776ea8dcd5ccdd1f0035d1',
      [TESTNET]: '',
    },
    tokenSymbol: 'IO',
    tokenAddresses: contracts.io,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 58,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'ZOD-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xf0caf168dd42b6181d3f11b703e358273b792935',
      [TESTNET]: '',
    },
    tokenSymbol: 'ZOD',
    tokenAddresses: contracts.zod,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 59,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'ZOD-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xb7bac60efe2dc0f4e0daab34e82c46892a6baa48',
      [TESTNET]: '',
    },
    tokenSymbol: 'ZOD',
    tokenAddresses: contracts.zod,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 60,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '3X',
    poolWeight: 300, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'ZOD',
    lpAddresses: contracts.zod,
    tokenLpAddresses: {
      [MAINNET]: '0xb7bac60efe2dc0f4e0daab34e82c46892a6baa48',
      [TESTNET]: '',
    },
    tokenSymbol: 'ZOD',
    tokenAddresses: contracts.zod,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 61,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    isRetired: true,
    lpSymbol: 'LUM-BNB LP',
    lpAddresses: {
      [MAINNET]: '0xb6b308c9c7c5f5cace704c86d4dfa4707a69fc87',
      [TESTNET]: '',
    },
    tokenSymbol: 'LUM',
    tokenAddresses: contracts.lum,
    quoteTokenSymbol: QuoteToken.BNB,
    quoteTokenAdresses: contracts.wbnb,
  },
  {
    fid: 0,
    pid: 62,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'LUM-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xd4c4168846efd2f3b8e169917713d59213a693b9',
      [TESTNET]: '',
    },
    tokenSymbol: 'LUM',
    tokenAddresses: contracts.lum,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 63,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'LUM',
    lpAddresses: contracts.lum,
    tokenLpAddresses: {
      [MAINNET]: '0xd4c4168846efd2f3b8e169917713d59213a693b9',
      [TESTNET]: '',
    },
    tokenSymbol: 'LUM',
    tokenAddresses: contracts.lum,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 64,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '64X',
    poolWeight: 6400,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'LO-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xc0af831c4dde1b1313da057fb7f5924f79f6087b',
      [TESTNET]: '',
    },
    tokenSymbol: 'LO',
    tokenAddresses: contracts.lo,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 65,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '3X',
    poolWeight: 300, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'LO',
    lpAddresses: contracts.lo,
    tokenLpAddresses: {
      [MAINNET]: '0xc0af831c4dde1b1313da057fb7f5924f79f6087b',
      [TESTNET]: '',
    },
    tokenSymbol: 'LO',
    tokenAddresses: contracts.lo,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 66,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '32X',
    poolWeight: 3200,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'KO-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xe9F6D18263732df2f8b9C2D45b07ca9D3a5dC7cA',
      [TESTNET]: '',
    },
    tokenSymbol: 'KO',
    tokenAddresses: contracts.ko,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 67,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'KO',
    lpAddresses: contracts.ko,
    tokenLpAddresses: {
      [MAINNET]: '0xe9F6D18263732df2f8b9C2D45b07ca9D3a5dC7cA',
      [TESTNET]: '',
    },
    tokenSymbol: 'KO',
    tokenAddresses: contracts.ko,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 68,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '128X',
    poolWeight: 12800,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'FAL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0x607738735F10dA3c7bcAb0FEaa509e6dF6b425F8',
      [TESTNET]: '',
    },
    tokenSymbol: 'FAL',
    tokenAddresses: contracts.fal,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 69,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: true,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'FAL',
    lpAddresses: contracts.fal,
    tokenLpAddresses: {
      [MAINNET]: '0x607738735F10dA3c7bcAb0FEaa509e6dF6b425F8',
      [TESTNET]: '',
    },
    tokenSymbol: 'FAL',
    tokenAddresses: contracts.fal,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 70,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '128X',
    poolWeight: 12800,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'PUL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0x186269f602a9c7bbe333d3c1bb88cc3277cb222a',
      [TESTNET]: '',
    },
    tokenSymbol: 'PUL',
    tokenAddresses: contracts.pul,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 71,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: true,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'PUL',
    lpAddresses: contracts.pul,
    tokenLpAddresses: {
      [MAINNET]: '0x186269f602a9c7bbe333d3c1bb88cc3277cb222a',
      [TESTNET]: '',
    },
    tokenSymbol: 'PUL',
    tokenAddresses: contracts.pul,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 72,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: true,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'UM',
    lpAddresses: contracts.um,
    tokenLpAddresses: {
      [MAINNET]: '0xf5fa8f27b09f9f449955e137d6dadfb9e086e3ac',
      [TESTNET]: '',
    },
    tokenSymbol: 'UM',
    tokenAddresses: contracts.um,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 73,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '128X',
    poolWeight: 12800,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'UM-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xf5fa8f27b09f9f449955e137d6dadfb9e086e3ac',
      [TESTNET]: '',
    },
    tokenSymbol: 'UM',
    tokenAddresses: contracts.um,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 74,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '512X',
    poolWeight: 51200,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'RXS-BUSD LP V2',
    lpAddresses: {
      [MAINNET]: '0xe576ebf57b3776f8892e2df1787cb163f41a1242',
      [TESTNET]: '',
    },
    tokenSymbol: 'RXS',
    tokenAddresses: contracts.rxs,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 75,
    risk: 6,
    isFinished: false,
    isStarting: false,
    multiplier: '2X',
    poolWeight: 200, // 50
    isTokenOnly: true,
    isHiddenPool: false,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'RXS',
    lpAddresses: contracts.rxs,
    tokenLpAddresses: {
      [MAINNET]: '0xe576ebf57b3776f8892e2df1787cb163f41a1242',
      [TESTNET]: '',
    },
    tokenSymbol: 'RXS',
    tokenAddresses: contracts.rxs,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 76,
    risk: 6,
    chefKey: CURRENT_FARM_SYMBOL,
    isFinished: false,
    isStarting: false,
    multiplier: '128X',
    poolWeight: 12800,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'MAL-BUSD LP',
    lpAddresses: {
      [MAINNET]: '0xac57acfd31bf2e399d194e2c4443d07c3248f5c5',
      [TESTNET]: '',
    },
    tokenSymbol: 'MAL',
    tokenAddresses: contracts.mal,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  {
    fid: 0,
    pid: 77,
    risk: 6,
    chefKey: CURRENT_FARM_SYMBOL,
    isFinished: false,
    isStarting: false,
    multiplier: '1X',
    poolWeight: 100, // 50
    isTokenOnly: true,
    isHiddenPool: true,
    depositFeeBP: 0,
    inactive: false,
    lpSymbol: 'MAL',
    lpAddresses: contracts.mal,
    tokenLpAddresses: {
      [MAINNET]: '0xac57acfd31bf2e399d194e2c4443d07c3248f5c5',
      [TESTNET]: '',
    },
    tokenSymbol: 'MAL',
    tokenAddresses: contracts.mal,
    quoteTokenSymbol: QuoteToken.BUSD,
    quoteTokenAdresses: contracts.busd,
  },
  // {
  //   fid: 0,
  //   pid: 72,
  //   risk: 6,
  //   isFinished: false,
  //   isStarting: false,
  //   multiplier: '48X',
  //   poolWeight: 4800,
  //   depositFeeBP: 0,
  //   inactive: false,
  //   lpSymbol: 'VEX-BUSD LP',
  //   lpAddresses: {
  //     [MAINNET]: '0xD0714ac44125eF1F5C11688dcb54507B06d621cA',
  //     [TESTNET]: '',
  //   },
  //   tokenSymbol: 'VEX',
  //   tokenAddresses: contracts.vex,
  //   quoteTokenSymbol: QuoteToken.BUSD,
  //   quoteTokenAdresses: contracts.busd,
  // },
  // {
  //   fid: 0,
  //   pid: 73,
  //   risk: 6,
  //   isFinished: false,
  //   isStarting: false,
  //   multiplier: '2X',
  //   poolWeight: 200, // 50
  //   isTokenOnly: true,
  //   isHiddenPool: true,
  //   depositFeeBP: 0,
  //   inactive: false,
  //   lpSymbol: 'VEX',
  //   lpAddresses: contracts.vex,
  //   tokenLpAddresses: {
  //     [MAINNET]: '0xD0714ac44125eF1F5C11688dcb54507B06d621cA',
  //     [TESTNET]: '',
  //   },
  //   tokenSymbol: 'VEX',
  //   tokenAddresses: contracts.vex,
  //   quoteTokenSymbol: QuoteToken.BUSD,
  //   quoteTokenAdresses: contracts.busd,
  // },
  // {
  //   fid: 0,
  //   pid: 72,
  //   risk: 6,
  //   chefKey: CURRENT_FARM_SYMBOL,
  //   isFinished: false,
  //   isStarting: false,
  //   multiplier: '128X',
  //   poolWeight: 12800,
  //   depositFeeBP: 0,
  //   inactive: false,
  //   lpSymbol: 'LEM-BUSD LP',
  //   lpAddresses: {
  //     [MAINNET]: '0x15af9019e796ac5f92eDF6c59D4B9C7c7A220811',
  //     [TESTNET]: '',
  //   },
  //   tokenSymbol: 'LEM',
  //   tokenAddresses: contracts.lem,
  //   quoteTokenSymbol: QuoteToken.BUSD,
  //   quoteTokenAdresses: contracts.busd,
  // },
  // {
  //   fid: 0,
  //   pid: 73,
  //   risk: 6,
  //   chefKey: CURRENT_FARM_SYMBOL,
  //   isFinished: false,
  //   isStarting: false,
  //   multiplier: '1X',
  //   poolWeight: 100, // 50
  //   isTokenOnly: true,
  //   isHiddenPool: true,
  //   depositFeeBP: 0,
  //   inactive: false,
  //   lpSymbol: 'LEM',
  //   lpAddresses: contracts.lem,
  //   tokenLpAddresses: {
  //     [MAINNET]: '0x15af9019e796ac5f92eDF6c59D4B9C7c7A220811',
  //     [TESTNET]: '',
  //   },
  //   tokenSymbol: 'LEM',
  //   tokenAddresses: contracts.lem,
  //   quoteTokenSymbol: QuoteToken.BUSD,
  //   quoteTokenAdresses: contracts.busd,
  // },
]

export default farms
